### PR TITLE
Match colons as part of path segments

### LINKED ISSUE #212: Configuration fails for ** when path includes colons
In our app, authentication was being set up using `service.configure("**") { ... }` as was recommended in the user guide. 

Fast forward and we implemented push notifications, and the way to delete a firebase token from the backend was to send a `DELETE` request to `/devices/<firebase token string>`

The request was failing with authentication errors. I tried to send the request through Paw and it succeeded without errors, so the backend was working fine.

I thought there was a race condition between signing out and deleting tokens but there seemed to be none. Setting up siesta logging to show configurations for requests, I noticed that the `**` configuration was being applied to all the requests except the token deletion request. Then I noticed that there was a colon `:` in the token, and I suspected it might be the cause. I stripped the `:` in the token string and the configuration was being applied to the request correctly.

I wanted to send a PR for this but I don't know much about regular expressions and it seems the matching is made with those.

### PR DESCRIPTION
**Pull request by pcantrell**
Siesta incorrectly treated `:` as a special URL component separator like `?` or `#`. That is incorrect; the HTTP spec considers colons a valid part of a path segment.

When configuring patterns, a path of `/f:oo/bar` should match:

- `/**`
- `/*/bar`
- `/f?oo/bar`

Fixes #212.

### CODE REVIEW

File: Tests/Functional/ServiceSpec.swift [hunk 1]
```diff
@@ -351,6 +364,11 @@ class ServiceSpec: SiestaSpec
                     checkPattern("/**x**",  matches: false, "/just/a/health/handful")
                     checkPattern("/**/*",   matches: true,  "/a/b")
                     checkPattern("/**/*",   matches: true,  "/ab")
+                    for funnyChar in funnyChars
+                        {
+                        checkPattern("/**/d", matches: true, "/a/b/\(funnyChar)/c/d")
+                        checkPattern("/**",   matches: true, "/a/b/\(funnyChar)/c/d")
```
Comment (akaralar) [inline Tests/Functional/ServiceSpec.swift]: I believe this most resembles my use case. If this passes then I guess my problem will be solved. Will let you know after this is merged.

**Comment by pcantrell** [comment]
Travis is freaking out on this PR, I think because I changed the base branch from `swift-4` to `master` so the fix for this could make it into 1.2.1, but it’s still building with Xcode 9. Anyway, I'm going to merge into master and see what disaster ensues. Yay!
