### PR TITLE
Fix cache check race condition

### LINKED ISSUE #237: Race condition between cache check and loadIfNeeded()
When instantiating a `Resource`, Siesta checks for cached data asynchronously, updating the resource later if there is a cache hit (and if the resource hasn’t loaded fresh data in the meantime). This is good, but it creates a race condition where `loadIfNeeded` may initiate a network request if called before the cache check is done.

Instead, `loadIfNeeded()` should return a chained request that _first_ waits for the cache check if there is one in progress, and only chains to the a network request if the we got a cache miss.

([Original SO question](https://stackoverflow.com/questions/47633211/can-i-get-siesta-to-look-at-my-persistent-cache-before-making-a-network-request/47662048))

### PR DESCRIPTION
**Pull request by pcantrell**
This fixes #237.

### CODE REVIEW

File: Source/Siesta/Resource/Resource.swift [hunk 1]
```diff
@@ -513,7 +538,7 @@ public final class Resource: NSObject
 
     private func receiveDataNotModified()
```
Comment (falcon283) [inline Source/Siesta/Resource/Resource.swift]: Hello @pcantrell may I ask the real purpose of `receiveDataNotModified()`.
I'm currently using Siesta 1.4.0 and reached this point as possible bug. The same will apply also on the latest 1.4.3 code.

`receiveDataNotModified()` as I understood is responsible to notify the observers that the resource data is still valid and will not be downloaded from the network. I'm totally ok with it but few line before the `latestData?.touch()` will actually change the local data and will update then the cache as well using a new timestamp.

The `touch()` will update the timestamp and the new timestamp will be cached despite no new data comes in from the backend. As a result the local cached data may never expire. 

It's a real corner case but I was able to reproduce it just running again the killed application right before the resource expirations time.
As example, if a resource expires in 5 days and the user get back to the application after 4 days, the app may have been killed by the OS because of memory pressure, the cached resource get a new timestamp, invalidating the 5 days expiration planned for the day after. As result `loadIfNeeded()` will not result in a network call for a total of 9 days, unless the occurrence repeat all over again.

Looks like that lines 543-546 are not necessary at all.
Am I wrong? Maybe I misunderstood the .notChanged use case?

I'm just able to fix it in my code replacing the default EntityCache `func updateEntityTimestamp(_ timestamp: TimeInterval, forKey key: CacheKey)` implementation with an empty implementation. Probably all of this is not necessary at all.

Thank you in advance

Comment (falcon283) [reply Source/Siesta/Resource/Resource.swift]: Ok thanks for the explanation. It makes sense. I was confused because receiveDataNotModified() got called only in the pointed case. At least i didn't found any other call in the Siesta codebase.
Probably something still planned to be introduced?

Anyway i will file the bug so you can keep track of it.
Thanks

Comment (pcantrell) [reply Source/Siesta/Resource/Resource.swift]: The other (original and primary) call is here: https://github.com/bustoutsolutions/siesta/blob/master/Source/Siesta/Resource/Resource.swift#L478

Comment (falcon283) [reply Source/Siesta/Resource/Resource.swift]: Oh nice, I missed it because I was searching for `receiveDataNotModified()`
Thanks for pointing it out.
